### ISSUE TITLE
NerdTreeTabsToggle not working

### ISSUE THREAD

**Issue by stefanfrede** [jistr/vim-nerdtree-tabs#44]
Hi,

I installed vim-nerdtree-tabs via vundle and I see it in my list of installed bundles but when I try to use it, e.g. NerdTreeTabsToggle, I get the message that it is not an editor command.

BTW I'm using vim inside the Mac Terminal.app.
- Stefan

**Comment by badpenguin** [comment]
@stefanfrede can you tell wich version of vim/python are you using? I've the same problem on Ubuntu Zesty

**Comment by stefanfrede** [comment]
Sorry, I stopped using the plugin a while ago.
