### ISSUE TITLE
g:nerdtree_tabs_autofind not working

### ISSUE THREAD

**Issue by jetpack01** [jistr/vim-nerdtree-tabs#63]
Hi

I put let g:nerdtree_tabs_autofind=1 in my ~./vimrc on Mac
Both Vim on console and MacVim seem to ignore that, in every situation...
I still need to invoke :NERDTreeTabsFind for getting the opened file highlighted in NERDTree.

Am I missing anything or is it a bug?

Thank you.

**Comment by joshglendenning** [comment]
It appears that NERDTreeFindFile is only called for this setting in the `s:BufReadHandler`, which doesn't get called for the file you load vim with, apparently. I was able to hack in a fix by putting the following in the `s:VimEnterHandler` (lines 467-513):

```vimscript
if g:nerdtree_tabs_autofind
  call s:NERDTreeFindFile()
  call s:NERDTreeUnfocus()
endif
```

**Comment by khalilgharbaoui** [comment]
@ joshglendenning your fix did the trick for me. maybe this could be added to master?

**Comment by jistr** [comment]
Merged.
