### ISSUE TITLE
Error with vim 7.4.1584

### ISSUE THREAD

**Issue by mamantoha** [jistr/vim-nerdtree-tabs#75]
I get this error `E116: Invalid arguments for function <SNR>45_NERDTreeToggleAllTabs` after `:NERDTreeTabsToggle`

**Comment by valentinrusu-movidius** [comment]
Same here, with latest vim from ArchLinux.
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 17 2016 10:50:13)

**Comment by mamantoha** [comment]
It was Vim related problem in Arch Linux.

Fixed in 7.4.1639.
