### ISSUE TITLE
strange display when I close tab

### ISSUE THREAD

**Issue by L-Jovi** [jistr/vim-nerdtree-tabs#84]
hi, thanks for your plugin, I encounter issue after below step

1. I open the file
2. type `T` create new tab
3. `gt` to new tab
4. `<Leader> + n` open the nerdtree (default not display)
5. I close the new tab
6. strange display as below image

![image](https://cloud.githubusercontent.com/assets/7262199/22684469/78727838-ed57-11e6-8770-c80a94bec9ad.png)

can you help me?  thanks for your time,

regards.

**Comment by deepsweet** [comment]
same here, have temporarily "fixed" it with `let g:nerdtree_tabs_synchronize_view = 0`.

**Comment by xguerin** [comment]
👍 Seems to be due to the last commit 72a14f5

**Comment by jistr** [comment]
@xguerin I tried reverting 72a14f5 locally to see if it makes a difference, but i couldn't see any. In my observation the difference is whether the cursor is in NERDTree window (-> bug triggered) or the file window (-> bug not triggered) when i call `:tabclose`. I get the same result with or without commit 72a14f5.

**Comment by xguerin** [comment]
@jistr I can indeed repeat the problem when the cursor is in the NERDTree window and I call `:tabclose`. However, the problem is also here when I am in the file window and I hit `:q`, most likely because of `g:nerdtree_tabs_autoclose = 1`.

**Comment by Xunius** [comment]
Same here. Just installed an hour ago, and the work-around by @deepsweet worked for me, except that upon close a tab (using `:q`), it jumps to the NERDtree window in the previous tab, rather than the file in the previous tab. Would be better to auto-focus on the file I assume?

**Comment by L-Jovi** [comment]
thanks @deepsweet,

@jistr and I wonder whether it's time to close issue XD.

**Comment by Xunius** [comment]
@L-Jovi you are not serious are you?

**Comment by hackhowtofaq** [comment]
Same problem here 72a14f5

![bug2](https://cloud.githubusercontent.com/assets/1138336/22936866/6f373294-f2df-11e6-92a4-eb91b883932a.gif)

**Comment by mhinton** [comment]
This happens to me every time I close a tab while in the file window.

**Comment by masongup-mdsol** [comment]
Happens to me too. I'm reverting my local back to 5a91230.

What I observe: Open Vim, Open Nerdtree, open a file in a new tab with `t`. Close that file with `:q`. Observe the nerdtree window in the other tab now expanded all the way across the screen.

**Comment by jistr** [comment]
Thanks for the report and confirmations, i reverted that commit, hopefully things are ok now.

**Comment by L-Jovi** [comment]
thanks again :)

**Comment by micbou** [comment]
Issue #76 should be reopened then.

**Comment by Felixoid** [comment]
May anyone test #92 for fix both this and #76 issues?
