### ISSUE TITLE
let g:nerdtree_tabs_open_on_gui_startup=0 does not persist between tabs

### ISSUE THREAD

**Issue by AndrewRayCode** [jistr/vim-nerdtree-tabs#9]
If you set `let g:nerdtree_tabs_open_on_gui_startup=0` in your .vimrc and then open NERDTree and press t on a file, it opens a new tab, but the tree is closed in the new tab. I don't want it to open on startup, but I do want it to open when creating a tab from nerdtree. Is this possible?

**Comment by jimafisk** [comment]
This is super helpful, that wasn't apparent to me either. Thanks for the help and awesome plugin @jistr!

For a little extra context, in `~/.vimrc` you've likely set a binding to open/close NERDTree, mine looked something like this:
```
map nt :NERDTreeToggle<CR>
```
Update that to:
```
map nt :NERDTreeTabsToggle<CR>
```
Now I can toggle NERDTree open by pressing "nt" and it will be open in all tabs, then toggle it close again across all tabs by pressing "nt" another time.
